services:
  - type: web
    name: ebay-render-endpoint
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: VERIFICATION_TOKEN
        value: mein_token_1234567890_1234567890
      - key: ENDPOINT
        value: https://ebay-render-endpoint.onrender.com/ebay-notify
